language: rust
rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get install -y libtbb-dev
  # get embree
  - sudo apt-get install -y alien dpkg-dev debhelper build-essential wget
  - wget https://github.com/embree/embree/releases/download/v3.2.0/embree-3.2.0.x86_64.rpm.tar.gz -O /tmp/embree.tar.gz
  - cd /tmp
  - tar -xvf embree.tar.gz
  - ls -la
  - sudo alien embree-lib-3.2.0-1.x86_64.rpm
  - sudo alien embree-devel-3.2.0-1.noarch.rpm
  - sudo dpkg -i embree-lib_3.2.0-2_amd64.deb
  - sudo dpkg -i embree-devel_3.2.0-2_all.deb
  - cd - # Go back to the working directory
  - RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org rustup install stable

script:
  - cargo build --verbose --all
  - cargo test --verbose --all